#! /usr/bin/env python3

import argparse
import sys
import os

blast_home = "/mnt/common/gtsw/pkg/ncbi-blast/default"

ap = argparse.ArgumentParser()
ap.add_argument("--evalue", type=float, default=0.005, help="evalue cutoff.")
ap.add_argument(
    "--format", choices=("standard", "tab"), default="tab", help="output format."
)
ap.add_argument("--query", help="FASTA query file, default stdin.")
ap.add_argument("subject", help="FASTA subject file.")
args = ap.parse_args()

if args.format == "tab":
    ofmt = 6
else:
    ofmt = 0

cmd = (
    f"{blast_home}/bin/blastn "
    f"-subject {args.subject} "
    f"-evalue {args.evalue} "
    f"-outfmt {ofmt}"
)

if not args.query:
    os.system(f"{cmd} -query -")
else:
    os.system(f"{cmd} -query {args.query}")
